#!/bin/bash

validateIPVFOUR(){
	if [ "${#1}" -gt "15" ]; then
		return 1;
	fi
	char="";
	array=();
	counter=0;
	lastnum=0;
	for (( i=0; i<${#1}; i++ )); do
		char="${1:$i:1}";
		if [ "$char" == "." ]; then
			diff=$((i-lastnum));
			array[counter]="${1:$lastnum:$diff}";
			counter=$((counter+1));
			lastnum=$((i+1));
		fi
	done
	if [ "$counter" -ne "3" ]; then
		return 1;
	fi
	len=${#1};
	diff=$((len-lastnum));
	array[counter]="${1:$lastnum:$diff}";
	counter=$((counter+1));	
	re='^[0-9]+$';
	for (( i=0; i<$counter; i++ )); do
		if [ "${#array[$i]}" -le "0" ] || [ ${#array[$i]} -gt "3" ]; then
			return 1;
		fi
		for (( j=0; j<${#array[$i]}; j++ )); do
			char="${array[$i]:$j:1}";
			if ! [[ $char =~ $re ]] ; then
				return 1; 
			fi	
		done
	done
	for (( i=0; i<$counter; i++ )); do
		if [ "${array[$i]}" -gt "255" ]; then
			return 1;
		fi
	done
	return 0;
}

listIPs(){
	clear
	printf "IP Addresses List\n";
	for ip in $data; do
		printf "$ip\n";
	done
	printf "\n";
}

addHosts(){
	listIPs
	printf "Please input ip addresses individually, press e then enter to exit\n";
	while true; do
		read input;
		if [ "$input" == "e" ]; then
			break;
		fi
		if validateIPVFOUR $input ; then
			printf "Valid IP $input\n";
			sh -c "echo '$input ' >> '$PWD/$filename'"; 
		else
			printf "Invalid IP $input, please try again\n";
		fi
	done
	data=$(cat $PWD/$filename);
}

removeHosts(){
	listIPs
	printf "Please input the ip addresses to remove, press e then enter to exit\n";
	while true; do
		read input;
		if [ "$input" == "e" ]; then
			break;
		fi
		sed -i "/$input /d" $PWD/$filename	
	done
	data=$(cat $PWD/$filename);
}

pingHosts(){
	for ip in $data; do
		result="$(ping -q -n -s 2 -W 2 -c 4 $ip)";
		result="${result##*-}";
		for part in $result; do
			if [[ "$part" == *"%"* ]]; then
				result=${part:0:(${#part}-1)};
				if [ "$result" -gt 25 ] && [ "$result" -lt 100 ]; then
					result="??";
				elif [ "$result" -eq 100 ]; then
					result="DOWN";
				else
					result="UP";	
				fi
				break;
			fi
		done
		statusarray[statuscounter]="$result";
		statuscounter=$((statuscounter+1));
	done
}

#Entry Point

if [ "$EUID" -ne 0 ]; then
	printf "Please run script as root\n"
	exit;
fi
clear

#Initializing global variables

configfilename="hoststatus.conf";
configdata="";
sendLogs="0";
filename="hostIPs";
data="";

#Load config file

if [ -f $PWD/$configfilename ]; then
	printf "Config file exists\nImporting data from file...\n";
	configdata=$(cat $PWD/$configfilename);
	printf "Done\n";
else
	printf "Config file does not exist\nCreating file...\n";
	touch $PWD/$configfilename
	printf "Done\nAppending default config settings...\n";
	sh -c "echo 'hostIPs_FileName=hostIPs ' >> '$PWD/$configfilename'";
	sh -c "echo 'writeLogsToSyslog=false ' >> '$PWD/$configfilename'";
	configdata=$(cat $PWD/$configfilename);
	printf "Done\n";
fi

#Load config settings

for config in $configdata; do
	pre=${config%=*};
	val=${config#*=};
	case $pre in
		hostIPs_FileName)
			filename="$val";
			;;
		writeLogsToSyslog)
			if [ "$val" == "true" ] || [ "$val" == "1" ]; then
				sendLogs="1";
			fi
			;;
		*)
			printf "Invalid config: $pre\n";
			;;
	esac
done
printf "\n";	

#Load host ips

if [ -f $PWD/$filename ]; then
	printf "$filename file exists\nImporting data from $filename...\n";
	data=$(cat $PWD/$filename);

	#Check if the user wants to add more host ips	

	printf "Done\n\nDo you want to add more host ips? [y/n]\n";
	read -t 3 input;
	if [ "$input" == "y" ]; then
		addHosts
	fi
else
	printf "$filename file does not exist\nCreating $filename...\n";
	touch $PWD/$filename
	printf "Done\n";
	addHosts
fi

#Check if user wants to remove host ips

printf "\nDo you want to remove host ips? [y/n]\n";
read -t 3 input;
if [ "$input" == "y" ]; then
	removeHosts
fi
clear

#Validating host ips

printf "Validating all ips in file...\n\n";
for ip in $data; do
	if ! validateIPVFOUR $ip ; then
		printf "INVALID IP!!! = $ip\n\nExiting!\n";
		exit;
	fi
	printf "$ip\n";
done
printf "\nValid ;)\n\nGathering initial data...";

#Start pinging hosts and output results to console

while true; do
	statusarray=();
	statuscounter=0;
	pingHosts	
	statuscounter=0;
	clear;
	printf "   __ __         __    ______       __         \n";
	printf "  / // /__  ___ / /_  / __/ /____ _/ /___ _____\n";
	printf " / _  / _ \\(_-</ __/ _\\ \\/ __/ _ \`/ __/ // (_-<\n";
	printf "/_//_/\\___/___/\\__/ /___/\\__/\\_,_/\\__/\\_,_/___/\n";
	printf "\n By Alex C.\n\n";
	printf " HOST                STATUS\n\n";
	for ip in $data; do
		printf " ";
		printf "%-15s" "$ip";
		printf "     ";
		if [ "$sendLogs" == "1" ]; then
			logger [HOSTSTATUS]: $ip is ${statusarray[$statuscounter]}		
		fi
		case ${statusarray[$statuscounter]} in
			UP)
				printf "\e[32;1mUP\e[0m\n";
				;;
			DOWN)
				printf "\e[31;1mDOWN\e[0m\n";
				;;
			??)
				printf "\e[33;1m??\e[0m\n";
				;;
		esac
		statuscounter=$((statuscounter+1));
	done
	date="$(date +'%H:%M:%S %D')";	
	printf "\n Last Updated: $date\n\n"
	printf "\n [To exit: Press e then enter] ";

	read -t 2 input;
	if [ "$input" == "e" ]; then
		break;
	fi		
	sleep 1;
done

printf "\n Done!\n\n "
